# This is a basic workflow to help you get started with Actions

name: Spring Boot CI with Gradle & Deploy to EC2

# develop 브랜치에 push가 되면 아래의 flow가 실행됨
on:
  pull_request:
    branches: [ "develop" ]

# flow에서 사용할 변수 같은 느낌입니다.
# jar 파일 빌드할 s3 버킷, aws 리전, CodeDeploy 앱 이름, 배포그룹이름
env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: 3dbox-github-actions-bucket
  CODE_DEPLOY_APPLICATION_NAME: 3dbox-codedeploy-app
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: 3dbox-codedeploy-deployment-group
  RESOURCE_PATH: ./src/main/resources/application-dev.yml
permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # 1) 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # 2) JDK 17 셋팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 2-1) Set yml file
      - name: Set yml file
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.RESOURCE_PATH }}
        env:
          spring.datasource.url: ${{ secrets.URL }}
          spring.datasource.username: ${{ secrets.RDS_USERNAME }}
          spring.datasource.password: ${{ secrets.RDS_PASSWORD }}
          cloud.aws.s3.bucket: ${{ secrets.BUCKET }}
          cloud.aws.s3.credentials.access-key: ${{ secrets.ACCESS_KEY }}
          cloud.aws.s3.credentials.secret-key: ${{ secrets.SECRET_KEY }}
          oauth2.google.client-id: ${{ secrets.CLIENT_ID }}
          oauth2.google.client-secret: ${{ secrets.CLIENT_SECRET }}

      # 3) gradlew 권한 설정
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4) test 제외 gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 5) AWS 인증
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 6) AWS S3에 업로드
      - name: Upload artifacts to AWS S3
        run: |
          aws deploy push \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --ignore-hidden-files \
          --s3-location s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip \
          --source .
#          zip -r deploy-package.zip .
#          aws s3 cp deploy-package.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip

      # 7) 기존 배포 중지
#      - name: Stop existing deployment if any
#        run: |
#          DEPLOYMENT_ID=$(aws deploy list-deployments \
#            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
#            --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
#            --include-only-statuses "Created" "Queued" "InProgress" \
#            --query "deployments[0]" \
#            --output text)
#          if [ "$DEPLOYMENT_ID" != "None" ]; then
#            echo "Stopping existing deployment: $DEPLOYMENT_ID"
#            aws deploy stop-deployment --deployment-id $DEPLOYMENT_ID
#            # 기다리는 시간 설정 (예: 30초)
#            sleep 30
#          fi

      # 7) AWS EC2에 Deploy
      - name: Deploy to AWS EC2 from S3
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=$S3_BUCKET_NAME,key=$GITHUB_SHA.zip,bundleType=zip